name: Test

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.11.3
      - name: Run tests
        run: sbt test
      - name: Run example tests
        run: |
          cd example
          sbt test
      - name: Run example-esbuild tests
        run: |
          cd example-esbuild
          sbt test
